apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor # this is an object specifically used with our kube-prometheus-stack helm chart
metadata:
  name: planetarium-service-monitor
  # namespace: default 
  labels:
    app: "planetarium"
spec:
  jobLabel: planetarium-app
  selector:
    matchLabels: 
      app: planetarium #THIS IS LOOKING AT THE SERVICE, IT'S A SERVICE MONITOR!
  endpoints:
  - port: http # this tells the service monitor to target a port with the name value of http
    path: /actuator/prometheus
    interval: 10s